apps/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from apps import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('testcase/<int:pk>', views.post_results, name='index2'),
    path('testcase/results/<int:pk>', views.result_list, name='index3'),
    path('testcase/results/detail/<int:pk>', views.view_detail, name='result-detail'),
    url('^$', views.runner_check, name='check'),
    path('testcase/index/', views.get_index, name='index'),
    path('testcase/new/', views.post_new, name='new'),
    path('testcase/edit/<id>/', views.post_edit, name='edit'),
    path('testcase/show/<id>/', views.detail, name='detail'),
    path('testcase/delete/<id>/', views.delete, name='delete'),
    path('testcase/run/<id>/<ip>/<port>', views.run_test, name='run')
]

config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

fadu_test_manager/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('runners/', include(('apps.urls', 'runners'), namespace="runners")),
    path('', include(('apps.urls', 'testcase'), namespace="testcase"))

]

apps/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField


class TestSuits(models.Model):
    id = models.AutoField(primary_key=True)
    Title = models.CharField(max_length=200)
    Description = models.CharField(max_length=200)
    io_tester = models.CharField(max_length=10)


class TestGroups(models.Model):
    id = models.AutoField(primary_key=True)
    Test_suits_id = models.ForeignKey(TestSuits, on_delete=models.CASCADE)
    Title = models.CharField(max_length=200)
    Description = models.CharField(max_length=200)
    Dependency_id = models.IntegerField()
    Configs = JSONField()


class TestCases(models.Model):
    id = models.AutoField(primary_key=True)
    # Test_group_id = models.ForeignKey(TestGroups, on_delete=models.CASCADE)
    Test_group_id = models.IntegerField()
    Title = models.CharField(max_length=200)
    Description = models.CharField(max_length=200)
    Configs = JSONField()


class TestErrorLogs(models.Model):
    test_cases = models.ForeignKey('TestCases', on_delete=models.CASCADE)
    Data = models.TextField()


class TestIoLogs(models.Model):
    test_cases = models.ForeignKey('TestCases', on_delete=models.CASCADE)
    Timestamp = models.IntegerField()
    Percentile = models.FloatField()
    Wr_iops = models.FloatField()
    Wr_throughput = models.FloatField()
    Wr_latency = models.FloatField()
    Rd_iops = models.FloatField()
    Rd_throughput = models.FloatField()
    Rd_latency = models.FloatField()


class TestSmartLogs(models.Model):
    test_cases = models.ForeignKey('TestCases', on_delete=models.CASCADE)
    Timestamp = models.DateTimeField()
    Data_units_read = models.IntegerField()


class Users(models.Model):
    id = models.AutoField(primary_key=True)

fadu_test_manager/models.py
from django.db import models

apps/forms.py
from django import forms
from .models import TestCases


class NewForm(forms.ModelForm):
    class Meta:
        model = TestCases
        fields = ('Title', 'Description', 'Configs')

apps/views.py
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from .models import TestIoLogs, TestCases
from django.shortcuts import render, redirect
import urllib.request
import json
from urllib.error import HTTPError, URLError
from .forms import NewForm
from collections import OrderedDict
import requests


@csrf_exempt
def post_results(request, pk):
    data = json.loads(request.body)
    data["test_cases_id"] = pk
    test = TestIoLogs.objects.create(**data)
    test.save()
    print("test")
    return HttpResponse(request.POST)


def result_list(request, pk):
    servers = list(TestCases.objects.values('Title', 'id'))
    print(servers)
    servers2 = {}
    servers2['datas'] = servers

    return render(request, 'results/result_form.html', servers2)


def view_detail(request, pk):
    data = TestIoLogs.objects.filter(test_cases_id=pk)
    data2 = {}
    data2['datas'] = data
    print(data2)
    return render(request, 'results/result_detail.html', data2)


def runner_check(request):
    URLs = ['http://localhost:3000', 'http://localhost:8000', 'http://localhost:5000']
    runners_data = []

    for url in URLs:
        ip = url.split('//')[1].split(':')[0]
        port = url.split(':')[2]
        req = urllib.request.Request(url + '/status')
        try:
            response = urllib.request.urlopen(req)
            data = response.read()
            encoding = response.info().get_content_charset('utf-8')
            info = json.loads(data.decode(encoding))
            status = "Successful"
        except HTTPError as e:
            status = "Failed"
            info = ""
        except URLError as e:
            status = "Failed"
            info = ""
        runners_data.append({'ip': ip, 'port': port, 'status': status, 'info': info})
    return render(request, 'apps/status.html', {'runners_data': runners_data})


def get_index(request):
    list = TestCases.objects.all().order_by('-pk')
    if request.method == "POST":
        status = request.POST
        return render(request, 'apps/index.html', {'list': list, 'status': status})
    else:
        return render(request, 'apps/index.html', {'list': list})


def detail(request, id):
    data = TestCases.objects.filter(id=id)
    return render(request, 'apps/detail.html', {'data_list': data})


def post_new(request):
    if request.method == "POST":
        request.POST._mutable = True
        post_value = request.POST
        post_value.update(Configs=json.dumps(post_value['Configs']))
        form = NewForm(post_value)
        if form.is_valid():
            post = form.save(commit=False)
            post.Test_group_id = 1
            post.save()
            return redirect('testcase:index')
    else:
        form = NewForm()
        return render(request, 'apps/new.html', {'form': form})


def post_edit(request, id):
    if request.method == "POST":
        request.POST._mutable = True
        post_value = request.POST
        post_value.update(Configs=json.dumps(post_value['Configs']))
        form = NewForm(post_value)
        if form.is_valid():
            post = form.save(commit=False)
            post.id = id
            post.Test_group_id = 3
            post.save()
            return redirect('testcase:index')
    else:
        row = TestCases.objects.get(id=id)
        form = NewForm(initial={'Title': row.Title, 'Description': row.Description, 'Configs': row.Configs})
        return render(request, 'apps/edit.html', {'form': form})


def delete(id):
    delete_value = TestCases.objects.get(id=id)
    delete_value.delete()
    return redirect('testcase:index')


def run_test(request, id, ip, port):
    data = TestCases.objects.get(id=id)
    configs = data.Configs.split(', ')
    dic_configs = OrderedDict()
    for list in configs:
        list = list.split(':')
        dic_configs[list[0]] = list[1]
    json_data = json.dumps(dic_configs)
    url = 'http://'+ip+':'+port+'/start'
    headers = {'content-type':'application/json'}
    res = requests.post(url, data = json_data, headers = headers)
    data = json.loads(res.text, object_pairs_hook=OrderedDict)
    return render(request, 'results/result_rawdata.html', {"dictionary": data})

apps/templates/apps/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>
<body>
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <h1>Script Detail</h1>
    <h1>{{ id }}</h1>
    <table class="table">
    <thead>
    <tr>
       <td>Title</td>
       <td>Description</td>
       <td>Configs</td>
    </tr>
    {% for data in data_list %}
    <tr>
       <td>{{ data.Title }}</td>
       <td>{{ data.Description }}</td>
       <td>{{ data.Configs }}</td>
    </tr>
    {% endfor %}
    </thead>
</table>
</body>
</html>

apps/templates/apps/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit</title>
</head>
<body>
    <h1> Edit / Update page</h1>
    <form method = "post">
        {%csrf_token%}
        {{form.as_p}}
        <div class = "button">
        <button type="submit"> Edit </button>
        </div>
    </form>
</body>
</html>

apps/templates/apps/index.html
<!DOCTYPE html>
<html lang="en">
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% load static %}
<head>
    <link rel="stylesheet" href="{% static 'css/apps.css' %}">
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>

    <ol class="breadcrumb">
        <li><a href="/runners">Home</a></li>
        <li><a href="/testcase/index">TestCase</a></li>
        <li><a href="/testcase/results/">Results</a></li>
    </ol>
    <div id="wrapper">
    <h1> Index page</h1>
    <div>
        <table class="table table-bordered" id="table">

            <thead>
                <td>INDEX</td>
                <td>TITLE</td>
            </thead>
        <tbody>
        {% csrf_token %}
        {% for list_index in list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ list_index.Title }}</td>
                <td><a href="/testcase/show/{{ list_index.id }}" class="btn btn-default" role="button">Show Detail</a></td>
                <td><a href="/testcase/edit/{{ list_index.id }}" class="btn btn-default" role="button">Edit</a></td>
                <td><a href="/testcase/delete/{{ list_index.id }}" class="btn btn-default" role="button">Delete</a></td>
                {% if status.ip != null %}
                  <td><a href="/testcase/run/{{ list_index.id }}/{{ status.ip }}/{{ status.port }}" class="btn btn-success" role="button">Run Test</a></td>
                {% else %}
                  <td></td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
        </table>
    </div>
    <div>
      <a href="/testcase/new" class="btn btn-default" role="button">Create</a>
    </div>
    <div>
      <a>IP : {{ status.ip }}, PORT : {{ status.port }}</a>
    </div>
</body>
</html>

apps/templates/apps/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create</title>
</head>
<body>
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <h1> Create / New page</h1>

    <form method = "post">
        {%csrf_token%}
        {{form.as_p}}
        <div class = "button">
        <button type="submit"> Create </button>
        </div>
    </form>
</body>
</html>

apps/templates/apps/status.html
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}

<!DOCTYPE html>
<head>
   <link rel="stylesheet" href="{% static 'css/apps.css' %}">
</head>
<body>
<ol class="breadcrumb">
 <li><a href="/">Home</a></li>
 <li><a href="testcase/index">TestCase</a></li>
 <li><a href="testcase/results/">Results</a></li>
</ol>
   <div id="wrapper">
   <h1>Test Runner List</h1>
   <table id="table" class="table table-bordered">
       <thead>
           <tr>
               <td>Index</td>
               <td>IP</td>
               <td>Port</td>
               <td>Connection Status</td>
               <td>OS</td>
               <td>Version</td>
               <td>Release</td>
           </tr>
       </thead>
       {% for runners in runners_data %}
           {% if runners.status == "Failed" %}
               <tr class="danger">
           {% else %}
               <tr class="info">
           {%  endif %}
               <td>{{ forloop.counter }}</td>
               <td>{{ runners.ip }}</td>
               <td>{{ runners.port }}</td>
               <td>{{ runners.status }}</td>
               <td>{{ runners.info.system }}</td>
               <td>{{ runners.info.version }}</td>
               <td>{{ runners.info.release }}</td>

           {% if runners.status != "Failed" %}
               <td>
                 <form action="/testcase/index/" method="POST">
                   {% csrf_token %}
                   <input type="hidden" name="ip" value="{{ runners.ip }}">
                   <input type="hidden" name="port" value="{{ runners.port }}">
                   <button type="submit" class="btn btn-success">SELECT</button>
                 </form>
               </td>
           {% else %}
               <td></td>
           {% endif %}
       {%  endfor %}
   </table>
   </div>
</body>
</html>

apps/templates/results/result_detail.html
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'css/apps.css' %}">
</head>
<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li><a href="/testcase/index">TestCase</a></li>
  <li><a href="">Results</a></li>
</ol>

<h1>Results</h1>

<table>
  <tr>
    <th>Timestamp</th>
    <th>Percentile</th>
    <th>Wr_iops</th>
    <th>Wr_throughput</th>
    <th>Wr_latency</th>
    <th>Rd_iops</th>
    <th>Rd_throughput</th>
    <th>Rd_latency</th>
  </tr>

    {% for result in datas %}
        <tr>
        <td>{{ result.Timestamp }}</td>
        <td>{{ result.Percentile }}</td>
        <td>{{ result.Wr_iops }}</td>
        <td>{{ result.Wr_throughput }}</td>
        <td>{{ result.Wr_latency }}</td>
        <td>{{ result.Rd_iops }}</td>
        <td>{{ result.Rd_throughput }}</td>
        <td>{{ result.Rd_latency }}</td>
        </tr>

    {% endfor %}
</table>

apps/templates/results/result_form.html
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'css/apps.css' %}">
</head>
    <ol class="breadcrumb">
        <li><a href="/">Home</a></li>
        <li><a href="/testcase/index">TestCase</a></li>
        <li><a href="/testcase/results/">Results</a></li>
        </ol>
<h1>Results</h1>
<ul>
    {% for result in datas %}
    <li>
       <a href="{% url 'runners:result-detail' result.id %}">{{ result.Title }}</a>
    </li>
    {% endfor %}
</ul>

apps/templates/results/result_rawdata.html
<h1>Results</h1>

<table>
  <tr>
    <th>Timestamp</th>
    <th>BW</th>
    <th>BW_dir</th>
    <th>IOPS</th>
    <th>IOPS_dir</th>
    <th>LAT</th>
    <th>LAT_dir</th>
  </tr>
    {% for key1, val1 in dictionary.items %}
        <tr>
        <td>{{ key1 }}</td>
        {% for key2, val2 in val1.items %}
            {% for key3, val3 in val2.items %}
                {% if key3 == "dir" %}
                    {% if val3 == "1" %}
                        <td>WRITE</td>
                    {% else %}
                        <td>READ</td>
                    {% endif %}
                {% else %}
                    <td>{{ val3 }}</td>
                {% endif %}
            {% endfor %}
        {% endfor %}
        </tr>
    {% endfor %}

</table>

fadu_test_manager/templates/results/result_form.html
<h1>Results</h1>
<ul>
    {% for result in datas %}
    <li>
       <a href="{% url 'result-detail' result.id %}">{{ result.Title }}</a>
    </li>
    {% endfor %}
</ul>